### ISSUE TITLE
radiobox style in view creation box on win

### ISSUE THREAD

**Issue by yubowenok** [ViDA-NYU/genotet#130]
![image](https://cloud.githubusercontent.com/assets/1314429/13322734/ca7a640e-dba3-11e5-934f-1a3e84e66de5.png)
I guess this is not happening on mac but the above is what I saw on win.

**Comment by yubowenok** [comment]
Also
![image](https://cloud.githubusercontent.com/assets/1314429/13322802/2e5db49e-dba4-11e5-9704-033c86fe6361.png)

**Comment by yubowenok** [comment]
Suggested fix:

``` html
<input type="radio" class="radio-inline" name="..." checked></label>
<label class="radio-inline radio-label">...</label>
```

``` css
.panel .radio-label,
#dialog .radio-label {
  padding-left: 5px;
  margin-right: 10px;
}
```
